#!/bin/bash

# $1 stationid

if [ -f "/var/run/khstreamer/$1.pid" ]; then
    STATION_PID=$(/bin/cat "/var/run/khstreamer/$1.pid")
    /bin/kill -9 $STATION_PID
    rm -rf "/var/run/khstreamer/$1.pid"
fi